export const SUBMIT_USER_FORM = 'SUBMIT_USER_FORM';
export const RECEIVE_CURRENCIES = 'RECEIVE_CURRENCIES';
export const SUBMIT_NEW_EXPENSE = 'SUBMIT_NEW_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
